user:
  target: default
  outputs:
    default:
      type: snowflake
      account: SFEDU02-ENB78898
      user: WOODCHUCK
      password: NWSN123syr
      role: TRAINING_ROLE
      database: ANALYTICS 
      warehouse: VBAY
      schema: KNIGHTS_WHO_SAY_NI 
