user:
  target: default
  outputs:
    default:
      type: snowflake
      account: SFEDU02-ENB78898
      user: WOODCHUCK
      password: NSWN123syr
      role: 
      database: CHINOOK
      warehouse: RAW # Specify your Snowflake warehouse here
      schema: CHINOOK
