version: 2

sources:
  - name: chinook
    database: raw
    schema: chinoook

    tables:
      - name: datedimension
        schema: chinook
        tables:
        - name: dim_invoice
          description: "Table containing invoice dimensions, including invoice details and metadata."
          columns:
            - name: customerid
              description: "Customer making the purchase."
            - name: invoiceid
              description: "The purchase identifier."
            - name: invoicedate
              description: "Date of purchase."
            - name: billingaddress
              description: "Customer's address."
            - name: billingcity
              description: "Customer's city."
            - name: billingstate
              description: "Customer's state."
            - name: billingcountry
              description: "Customer's country."
            - name: billingpostalcode
              description: "Customer's postal code."
            - name: Total
              description: "Total $ amount of the purchase."
        - name: dim_customer
          description: "Table containing customer dimensions, including demographic and contact information."
          columns:
            - name: customerid
              description: "Primary key of the source systems (business key)."
            - name: firstname
              description: "Customer's first name."
            - name: lastname
              description: "Customer's last name."
            - name: company
              description: "Customer's company."
            - name: address
              description: "Customer's address."
            - name: city
              description: "Customer's city."
            - name: state
              description: "Customer's state."
            - name: country
              description: "Customer's country."
            - name: postalcode
              description: "Customer's postal code."
            - name: phone
              description: "Customer's phone."
            - name: fax
              description: "Customer's fax."
            - name: email
              description: "Customer's email."
            - name: supportrepid
              description: "Employee who helped with the purchase."

