version: 2

sources:
  - name: chinook
    database: raw
    schema: chinoook

    tables:
      - name: DateDimension
        columns:
          - name: DateKey
            tests:
              - unique
